[MIG] hr_employee_firstname: Migration to 17.0
Vauxoo/hr pull request #25
Opened 2023-11-06 20:51 UTC by andreagidaltig

- Update definition of required modifier as part of [1].
- Update incoming parameters of post_init_hook method since `cr, registry`
  were replaced by `env` in [2].

[1] https://github.com/odoo/odoo/pull/104741
[2] https://github.com/odoo/odoo/commit/b4a7996

2023-11-08 18:11 UTC, andreagidaltig commented
Hi @luistorresm could you review this please?

2023-11-08 18:17 UTC, luistorresm commented
Hello @andreagidaltig 

Could you join the commits related, please?

More info [here](https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate)

cc @luisg123v

2023-11-08 23:01 UTC, andreagidaltig commented
Hi @luistorresm 

I verified this with @luisg123v  and I just merged some translation commits from same author and same language as is indicated [here](https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate).

2023-11-09 04:52 UTC, luistorresm commented
👍 

@luisg123v 

Could you merge, please?

Regards

2023-11-13 05:38 UTC, luisg123v requested changes

2023-11-13 05:38 UTC, luisg123v commented on hr_employee_firstname/tests/test_hr_employee_firstname.py
> +        field_onchange = self.env["hr.employee"].new({})._get_fields_spec()
This is not an onchange anymore AFAIK, so I think you shouldn't neither name it as so nor using `new()`.

2023-11-13 05:38 UTC, luisg123v commented on hr_employee_firstname/tests/test_hr_employee_firstname.py
> +            submap(field_onchange, ('firstname', 'lastname')),
Why this?

2023-11-13 05:39 UTC, luisg123v commented
Missing task ID on PR's title.

2023-11-14 19:29 UTC, andreagidaltig commented
Hi @luisg123v I just modified this, could you review it again please?

cc. @luistorresm

2023-11-14 19:52 UTC, luisg123v approved these changes
LGTM :+1:

2023-11-14 19:53 UTC, merged

2023-11-14 19:54 UTC, luisg123v commented
Be aware once the OCA releases their branches, this will get overwritten and we will need to make a new PR targeting the OCA.